name: generate
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      - name: Setup neovim
        uses: rhysd/action-setup-vim@b7934f0630263431f328b14fdd86c788f3fadbc8
        with:
          neovim: true
      - name: Generate
        shell: bash
        run: make generate
      - name: Run tests
        shell: bash
        run: make test
      - name: Commit and Push Changes
        shell: bash
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update SchemaStore catalog" -m "This commit was performed automatically by GitHub Actions."
            git push
          fi
